version: '3.8'
services:
  neo4j:
    image: neo4j:5.12.0
    container_name: skillbarter-neo4j
    ports:
      - "7475:7474" # HTTP
      - "7688:7687" # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - ./data:/data
      - ./logs:/logs
